# Generated by Django 6.0.5 on 2026-05-07 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='behaviour_score',
            new_name='marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stress_score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_hours',
        ),
        migrations.AddField(
            model_name='student',
            name='discipline_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='StudentWellbeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad'), ('Anxious', 'Anxious')], default='Neutral', max_length=50)),
                ('stress_level', models.IntegerField(default=0)),
                ('sleep_quality', models.IntegerField(default=0)),
                ('social_activity', models.IntegerField(default=0)),
                ('motivation_level', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
