# Generated by Django 6.0.5 on 2026-05-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_read',
        ),
        migrations.AddField(
            model_name='alert',
            name='risk_level',
            field=models.CharField(default='Low', max_length=20),
            preserve_default=False,
        ),
    ]
