# Generated by Django 6.0.5 on 2026-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_alert_is_read_alert_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
