# Generated by Django 6.0.5 on 2026-05-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='recommendation',
        ),
    ]
