# Generated by Django 6.0.5 on 2026-05-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='discipline_score',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='motivation_level',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='sleep_quality',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='social_activity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='stress_level',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='RiskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=20)),
                ('risk_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='WellbeingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=50)),
                ('stress_level', models.FloatField()),
                ('sleep_quality', models.FloatField()),
                ('social_activity', models.FloatField()),
                ('motivation_level', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
