# Generated by Django 6.0.5 on 2026-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alert_is_resolved_alert_priority_student_risk_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwellbeing',
            name='mood',
            field=models.CharField(default='Neutral', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='motivation_level',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='sleep_quality',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='social_activity',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='stress_level',
            field=models.IntegerField(default=50),
        ),
    ]
