# Generated by Django 6.0.5 on 2026-05-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_studentwellbeing_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwellbeing',
            name='mood',
            field=models.CharField(default='Neutral', max_length=50),
        ),
    ]
