# Generated by Django 6.0.5 on 2026-05-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_studentwellbeing_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskhistory',
            name='student',
        ),
        migrations.RemoveField(
            model_name='wellbeinghistory',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='discipline_score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentwellbeing',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='student',
            name='discipline',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='risk_level',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='mood',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='motivation_level',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='sleep_quality',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='social_activity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='stress_level',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='RiskHistory',
        ),
        migrations.DeleteModel(
            name='WellbeingHistory',
        ),
    ]
