# Generated by Django 6.0.5 on 2026-05-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_riskhistory_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwellbeing',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad'), ('Anxious', 'Anxious')], default='Neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='motivation_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='sleep_quality',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='social_activity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='stress_level',
            field=models.IntegerField(default=5),
        ),
    ]
