# Generated by Django 6.0.5 on 2026-05-13 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ai_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='risk_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentwellbeing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='discipline',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studentwellbeing',
            name='mood',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
