# Generated by Django 6.0.5 on 2026-05-14 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('students', '0014_student_ai_recommendation_student_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
