# Generated by Django 6.0.5 on 2026-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_counsellingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
