# Generated by Django 6.0.5 on 2026-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_faculty_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellingsession',
            name='faculty_name',
            field=models.CharField(max_length=200),
        ),
    ]
