# Generated by Django 6.0.5 on 2026-05-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_counsellingsession_faculty_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellingsession',
            old_name='notes',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='counsellingsession',
            name='faculty_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
